# meta
verbose: true
seed : 42
# masses on springs with varying drag, c
models: ["lupi"]
use_saved_models: false
# data
use_saved_data: false
simulator:
  dt: 0.01
  sampling_freq : 20
  samples : 15
# evaluation
z_samples : 32
context_range : [1,5]
target_range : [6,16]
mse : true
calibration : true
calibration_bins : 32
sharpness : true


x_dim : 76
obs_enc_h_dim : 75
r_dim : 75
pi_dim : 49
pi_enc_h_dim : 49
pi_r_dim : 49
agg_h_dim : 75
aggregators : ["mean", "max"]
r_to_z_h_dim : 16
z_dim : 16
L_dim : 16
z_to_L_h_dim : 16
ode_h_dim : 16
dec_h_dim : 16
